version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: todo_api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://todo_user:todo_password@postgres:5432/todo_db
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app

volumes:
  postgres_data:
